language: node_js
node_js:
  - "10"
  - "11"

cache:
  directories:
    - "node_modules"

install:
  - yarn install
  - yarn build --modern=client

script:
  - yarn start -- --silent &
  - yarn cypress run
