language: node_js
node_js:
  - 10
  - 11

cache:
  directories:
    - node_modules
    - $HOME/.cache/Cypress

install:
  - yarn install
  - yarn global add codecov
  - yarn build --modern=client

script:
  - yarn start -- --silent &
  - yarn cypress run

after_success:
  - codecov
